--------------------------------------------------
-- lifebook 계정에서 실행되어야 하는 스크립트입니다. --
--------------------------------------------------

-- board 테이블 생성
  CREATE TABLE "LIFEBOOK"."BOARD" 
   (	"USER_ID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"B_TITLE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"B_CONTENT" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
	"B_NUMBER" NUMBER(5,0) NOT NULL ENABLE, 
	"B_HIT" NUMBER(5,0) DEFAULT 0, 
	"B_DATE" DATE, 
	"B_PUSH" NUMBER(3,0) DEFAULT 0, 
	 CONSTRAINT "BOARD_PK" PRIMARY KEY ("B_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKSTORE_TABLESPACE"  ENABLE, 
	 CONSTRAINT "BOARD_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "LIFEBOOK"."USERINFO" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKSTORE_TABLESPACE" ;

--책 정보 테이블 생성
  CREATE TABLE "LIFEBOOK"."BOOKINFO" 
   (	"BOOK_NUMBER" NUMBER(10,0) NOT NULL ENABLE, 
	"BOOK_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"BOOK_PRICE" NUMBER(6,0) NOT NULL ENABLE, 
	"BOOK_INFO" VARCHAR2(3000 BYTE), 
	"BOOK_IMG" VARCHAR2(3000 BYTE), 
	"BOOK_PUB" VARCHAR2(50 BYTE), 
	"BOOK_AUTHOR" VARCHAR2(30 BYTE), 
	"BOOK_STOCK" NUMBER(4,0), 
	 CONSTRAINT "bookinfo_PK" PRIMARY KEY ("BOOK_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKSTORE_TABLESPACE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKSTORE_TABLESPACE" ;

--공지사항 테이블 생성
  CREATE TABLE "LIFEBOOK"."NOTICE" 
   (	"N_TITLE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"N_CONTENT" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
	"N_NUMBER" NUMBER(5,0), 
	"USER_ID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "NOTICE_NUMBER_PK" PRIMARY KEY ("N_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKSTORE_TABLESPACE"  ENABLE, 
	 CONSTRAINT "NOTICE_USERINFO_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "LIFEBOOK"."USERINFO" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKSTORE_TABLESPACE" ;

--주문 테이블 생성
  CREATE TABLE "LIFEBOOK"."ORDER_TABLE" 
   (	"ORDER_NUMBER" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"BOOK_NUMBER" NUMBER(10,0) NOT NULL ENABLE, 
	"ORDER_AMOUNT" NUMBER(3,0) NOT NULL ENABLE, 
	"ORDER_DATE" DATE DEFAULT sysdate, 
	"ORDER_STATEMENT" VARCHAR2(10 BYTE), 
	 CONSTRAINT "ORDER_PK" PRIMARY KEY ("ORDER_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKSTORE_TABLESPACE"  ENABLE, 
	 CONSTRAINT "ORDER_USERINFO_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "LIFEBOOK"."USERINFO" ("USER_ID") ENABLE, 
	 CONSTRAINT "order_booknumber" FOREIGN KEY ("BOOK_NUMBER")
	  REFERENCES "LIFEBOOK"."BOOKINFO" ("BOOK_NUMBER") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKSTORE_TABLESPACE" ;

--유저 정보 테이블 생성
  CREATE TABLE "LIFEBOOK"."USERINFO" 
   (	"USER_ID" VARCHAR2(15 BYTE), 
	"USER_PWD" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"USER_PHONENUMBER" VARCHAR2(15 BYTE), 
	"USER_ADDRESS" VARCHAR2(100 BYTE), 
	"USER_BIRTHDATE" DATE, 
	"USER_MILEAGE" NUMBER(7,0) DEFAULT 0, 
	"ADMINYN" NUMBER(1,0) DEFAULT 0, 
	"USER_NAME" VARCHAR2(15 BYTE), 
	 CONSTRAINT "USERINFO_USERID_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKSTORE_TABLESPACE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKSTORE_TABLESPACE" ;

--유저 상세정보 테이블

  CREATE TABLE "LIFEBOOK"."USER_DETAIL" 
   (	"USER_ID" VARCHAR2(15 BYTE), 
	"BOOK_AMOUNT" NUMBER(3,0), 
	"BOOK_NUMBER" NUMBER(10,0), 
	 CONSTRAINT "USER_DETAIL_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "LIFEBOOK"."USERINFO" ("USER_ID") ENABLE, 
	 CONSTRAINT "USER_DETAIL_FK_BOOKNUM" FOREIGN KEY ("BOOK_NUMBER")
	  REFERENCES "LIFEBOOK"."BOOKINFO" ("BOOK_NUMBER") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOOKSTORE_TABLESPACE" ;



-- 주문관리용 뷰 생성

  CREATE OR REPLACE FORCE VIEW "LIFEBOOK"."V_ORDER" ("ORDER_NUMBER", "ORDER_DATE", "USER_ID", "USER_NAME", "USER_PHONENUMBER", "USER_ADDRESS", "BOOK_NUMBER", "BOOK_NAME") AS 
  select o.order_number
     , o.order_date
     , u.user_id
     , u.user_name
     , u.user_phonenumber
     , u.user_address
     , o.book_number
     , b.book_name
from order_table o join userinfo u
on o.user_id = u.user_id
join bookinfo b
on o.book_number = b.book_number;


