--------------------------------------------------
-- lifebook 계정에서 실행되어야 하는 스크립트입니다. --
--------------------------------------------------

--유저 정보 테이블 생성

  CREATE TABLE "LIFEBOOK"."USERINFO" 
   (	"USERID" VARCHAR2(15 BYTE), 
	"USERPWD" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(15 BYTE), 
	"USERPHONENUM" VARCHAR2(15 BYTE), 
	"USERADDR" VARCHAR2(100 BYTE), 
	"USERBIRTH" DATE, 
	"POINT" NUMBER(7,0) DEFAULT 0, 
	"ISADMIN" NUMBER(1,0) DEFAULT 0, 
	 CONSTRAINT "USERINFO_USERID_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK" ;


--책 정보 테이블 생성
 
  CREATE TABLE "LIFEBOOK"."BOOKINFO" 
   (	"BOOKNUM" NUMBER(10,0) NOT NULL ENABLE, 
	"BOOKNAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"BOOKDETAILS" VARCHAR2(3000 BYTE), 
	"BOOKPRICE" NUMBER(6,0) NOT NULL ENABLE, 
	"BOOKPUB" VARCHAR2(50 BYTE), 
	"AUTHOR" VARCHAR2(30 BYTE), 
	"BOOKIMG" VARCHAR2(3000 BYTE), 
	"BOOKSTOCK" NUMBER(4,0), 
	 CONSTRAINT "BOOKINFO_PK_BOOKNUM" PRIMARY KEY ("BOOKNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK" ;


-- 게시판 테이블 생성

  CREATE TABLE "LIFEBOOK"."BOARD" 
   ("BOARDNUM" NUMBER(5,0) NOT NULL ENABLE, 
    "USERID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"BOARDTITLE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"BOARDCONTENT" VARCHAR2(3000 BYTE) NOT NULL ENABLE,
    "REGDATE" DATE DEFAULT SYSDATE, 
    "USERIP" VARCHAR2(15 BYTE),
	"FILENAME" VARCHAR2(100 BYTE), 
	"FILESIZE" NUMBER(5,0), 
	"REALFILENAME" VARCHAR2(100 BYTE), 
	"HITCNT" NUMBER(5,0) DEFAULT 0, 
	"RECOMMEND" NUMBER(3,0) DEFAULT 0, 
	 CONSTRAINT "PK_BOARD_BOARDNUM" PRIMARY KEY ("BOARDNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK" ;

-- 댓글 테이블 생성

  CREATE TABLE "LIFEBOOK"."BOARDCOMMENT" 
   (	"CMTNUM" NUMBER(9,0) NOT NULL ENABLE, 
	"BOARDNUM" NUMBER(9,0) NOT NULL ENABLE, 
	"CMTCONTENT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"USERIP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_BOARDCOMMENT_CMTNUM" PRIMARY KEY ("CMTNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK"  ENABLE, 
	 CONSTRAINT "FK_BOARDCOMMEN_BOARDNUM" FOREIGN KEY ("BOARDNUM")
	  REFERENCES "LIFEBOOK"."BOARD" ("BOARDNUM") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK" ;

--공지사항 테이블 생성

  CREATE TABLE "LIFEBOOK"."NOTICE" 
   (	"NOTICENUM" NUMBER(5,0), 
	"USERID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"NOTICETITLE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"NOTICECONTENT" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
	"REGDATE" DATE, 
	"HITCNT" NUMBER(5,0) DEFAULT 0, 
	 CONSTRAINT "NOTICE_NUMBER_PK_NOTICENUM" PRIMARY KEY ("NOTICENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK" ;

--주문 테이블 생성

  CREATE TABLE "LIFEBOOK"."ORDER_TABLE" 
   (	"ORDERNUM" NUMBER(10,0) NOT NULL ENABLE, 
	"USERID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"BOOKNUM" NUMBER(10,0) NOT NULL ENABLE, 
	"ORDERDATE" DATE DEFAULT sysdate, 
	"ORDERRECIPIENT" VARCHAR2(15 BYTE), 
	"ORDERPHONENUM" VARCHAR2(15 BYTE), 
	"ORDERADDR" VARCHAR2(100 BYTE), 
	"AMOUNT" NUMBER(3,0) NOT NULL ENABLE, 
	"STATEMENT" VARCHAR2(10 BYTE) DEFAULT '준비중', 
	 CONSTRAINT "ORDER_PK" PRIMARY KEY ("ORDERNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK"  ENABLE, 
	 CONSTRAINT "ORDER_USERINFO_FK" FOREIGN KEY ("USERID")
	  REFERENCES "LIFEBOOK"."USERINFO" ("USERID") ENABLE, 
	 CONSTRAINT "order_booknumber" FOREIGN KEY ("BOOKNUM")
	  REFERENCES "LIFEBOOK"."BOOKINFO" ("BOOKNUM") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK" ;


-- 장바구니 테이블 생성

  CREATE TABLE "LIFEBOOK"."CART" 
   (	"USERID" VARCHAR2(15 BYTE), 
	"BOOKNUM" NUMBER(10,0), 
	"TOTALPRICE" NUMBER(7,0) DEFAULT 0, 
	"QUANTITY" NUMBER(3,0), 
	 FOREIGN KEY ("USERID")
	  REFERENCES "LIFEBOOK"."USERINFO" ("USERID") ENABLE, 
	 FOREIGN KEY ("BOOKNUM")
	  REFERENCES "LIFEBOOK"."BOOKINFO" ("BOOKNUM") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK" ;

--FAQ 테이블 생성

  CREATE TABLE "LIFEBOOK"."FAQ" 
   (	"FAQNUM" NUMBER(3,0), 
	"FAQCATEGORY" VARCHAR2(21 BYTE), 
	"FAQTITLE" VARCHAR2(200 BYTE), 
	"FAQCONTENT" VARCHAR2(3500 BYTE), 
	"RAGDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIFEBOOK" ;

-- 주문관리용 뷰 생성

  CREATE OR REPLACE FORCE VIEW "LIFEBOOK"."V_ORDER" ("ORDERNUM", "ORDERDATE", "USERID", "ORDERRECIPIENT", "ORDERPHONENUM", "ORDERADDR", "AMOUNT", "BOOKNUM", "BOOKNAME", "BOOKIMG") AS 
  select o.ordernum
     , o.orderdate
     , u.userid
     , o.orderrecipient
     , o.ORDERPHONENUM
     , o.ORDERADDR
     , o.amount
     , o.booknum
     , b.bookname
     , b.bookimg
from order_table o join userinfo u
on o.userid = u.userid
join bookinfo b
on o.booknum = b.booknum;
